### ISSUE TITLE
Unable to parse ontology with Pronto

### ISSUE THREAD

**Issue by Zethson** [DiseaseOntology/HumanDiseaseOntology#1112]
Hi,

I'm unable to parse this ontology with [Pronto](https://github.com/althonos/pronto) which is the major tool to load ontologies in Python:

`ontology = Ontology("doid.owl")`

results in
```

Traceback (most recent call last):
  File "/home/zeth/PycharmProjects/bionty/test.py", line 8, in <module>
    ontology = Ontology("/home/zeth/Downloads/doid.owl")
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py", line 283, in __init__
    cls(self).parse_from(_handle)  # type: ignore
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/parsers/rdfxml.py", line 95, in parse_from
    self.process_imports(
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/parsers/base.py", line 70, in process_imports
    return dict(pool.map(lambda i: (i, process(i)), imports))
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/parsers/base.py", line 70, in <lambda>
    return dict(pool.map(lambda i: (i, process(i)), imports))
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/parsers/base.py", line 49, in process_import
    return Ontology(url, max(import_depth - 1, -1), timeout)
  File "/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py", line 286, in __init__
    raise ValueError(f"could not find a parser to parse {handle!r}")
ValueError: could not find a parser to parse 'http://purl.obolibrary.org/obo/doid/obo/ext.owl'
```

Do you have any idea why HDO cannot be loaded with Pronto? It is the first ontology that I run into that doesn't work

**Comment by Zethson** [comment]
`https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/main/src/ontology/releases/HumanDO.owl`

still works with
```

/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: NotImplementedWarning: cannot process plain `owl:AnnotationProperty`
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/parsers/rdfxml.py:117: SyntaxWarning: unknown element in `owl:Class`: {http://www.w3.org/2004/02/skos/core#}exactMatch
  self._extract_term(class_, curies)
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'IAO:0000119'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'IAO:0000700'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://purl.org/dc/elements/1.1/description'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://purl.org/dc/elements/1.1/title'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://purl.org/dc/elements/1.1/type'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://purl.org/dc/terms/license'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#SubsetProperty'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#created_by'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#creation_date'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#date'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#default-namespace'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#hasAlternativeId'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#hasDbXref'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#hasExactSynonym'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#hasOBOFormatVersion'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#hasOBONamespace'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#id'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#inSubset'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.geneontology.org/formats/oboInOwl#saved-by'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2000/01/rdf-schema#comment'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2000/01/rdf-schema#label'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2002/07/owl#deprecated'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2002/07/owl#maxQualifiedCardinality'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2002/07/owl#minQualifiedCardinality'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2002/07/owl#qualifiedCardinality'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2004/02/skos/core#broadMatch'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2004/02/skos/core#closeMatch'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2004/02/skos/core#exactMatch'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2004/02/skos/core#narrowMatch'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2004/02/skos/core#relatedMatch'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: unknown axiom property: 'http://www.w3.org/2000/01/rdf-schema#comment'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'IAO:0000231'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2002/07/owl#backwardCompatibleWith'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2002/07/owl#incompatibleWith'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2002/07/owl#priorVersion'
  cls(self).parse_from(_handle)  # type: ignore
/home/zeth/miniconda3/envs/bionty/lib/python3.10/site-packages/pronto/ontology.py:283: SyntaxWarning: could not find axiom source: 'http://www.w3.org/2002/07/owl#versionInfo'
  cls(self).parse_from(_handle)  # type: ignore
```

**Comment by Zethson** [comment]
Your obo file still seems to work though

**Comment by allenbaron** [comment]
Lukas,
Thanks for pointing this out and for sharing the error. Can you tell me a little more about your setup? For example, if you're accessing local files and how they are organized? 

It looks like the error is not in doid.owl itself but caused by pronto's inability to parse ext.owl which is another file that doid.owl imports. That file is currently stored in OWL functional format and not RDF/XML. Now that we're aware of this issue we've decided to switch ext.owl to RDF/XML to remove these problems in the future.

This may or may not solve your problem loading doid.owl but I'd recommend using a different file anyway. If you can tell me a little about your application I might be able to suggest a file that would be more appropriate.

**Comment by Zethson** [comment]
Thank you very much for the fast answer!

> Can you tell me a little more about your setup? For example, if you're accessing local files and how they are organized?

I'm accessing the file locally on a Linux system.

> If you can tell me a little about your application I might be able to suggest a file that would be more appropriate.

We're developing [bionty](https://github.com/laminlabs/bionty) which is supposed to provide a unified API to load (biological) ontologies to curate (biological) terms. We download the ontologies in owl format lazily on request.

**Comment by allenbaron** [comment]
Thanks for sharing. I think the problem should be resolved for future releases but if you find there are still issues please let reply here and let us know. We really appreciate you pointing it out since we don't use pronto.

If the end goal is providing biological entities for curation you could likely improve performance by using the `*-base.owl` files (e.g. doid-base.owl, hpo-base.owl) for those ontologies that are part of the OBO Foundry. Most ontologies produce this file at each release but some that are simpler do not (i.e. Symptom Ontology and Pathogen Transmission Ontology).

These `*-base.owl` files are smaller and include details for ONLY the classes in the namespace of each ontology, as opposed to the main files that include classes imported from other ontologies used to create logical relationships. Using the base file has the added benefit of not loading the same information multiple times from different ontologies.

For example, the main Uberon file (uberon.owl) is ~ 20 MB larger than the base file (uberon-base.owl) and contains classes from BFO, CARO, FMA, OBI, PCO, PO, RO and SO that uberon-base.owl does not. uberon.owl also includes detailed information for classes from CL and other ontologies that are not in the uberon-base.owl file and would be better to get from CL directly (particularly for curation purposes).

**Comment by Zethson** [comment]
Excellent, thank you very much for pointing this out. This is very helpful for us. Thanks!

**Comment by lschriml** [comment]
@Zethson -- Would love to hear about your project and how you are using the DO. 

Cheers,
Lynn

**Comment by Zethson** [comment]
@lschriml I'm a PhD student in bioinformatics & ML and a research software engineer at https://lamin.ai/ which is a startup that focuses on data management in biology.

Long story short: We noticed that in our field progress is not hampered by talent or analysis tooling, but much rather scattered, untracked and differently labeled data. Hence, we're building primarily building open-source tooling to improve this. All of our tools will be connected via a database that manages everything. The "differently labeled data" issue is being tackled by [bionty](https://github.com/laminlabs/bionty) which provides access to several ontologies and curates existing data.

If you want more details please send me an email (see my profile) and I'll happily greatly expand.
