### ISSUE TITLE
pronto.Ontology can't parse HumanDo.obo file

### ISSUE THREAD

**Issue by lingling93** [DiseaseOntology/HumanDiseaseOntology#775]
When I try to use pronto.Ontology() to parse HumanDo.obo. I always get errors.

Here is the code:
`from pronto import Ontology
doo = Ontology("https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/HumanDO.obo")`

Here is the error:

Traceback (most recent call last):

  File "/Users/work/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-15-802c631a776b>", line 1, in <module>
    doo = Ontology("https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/HumanDO.obo")

  File "/Users/work/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/pronto/ontology.py", line 174, in __init__
    self._build_subclassing_cache()

  File "/Users/work/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/contexter.py", line 96, in __exit__
    reraise(exc)

  File "/Users/work/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/contexter.py", line 26, in reraise
    raise exc[1].with_traceback(exc[2])

  File "/Users/work/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/pronto/ontology.py", line 167, in __init__
    cls(self).parse_from(_handle)

  File "/Users/work/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages/pronto/parsers/obo.py", line 36, in parse_from
    raise SyntaxError(s.args[0], location) from None

  File "https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/HumanDO.obo", line 107679
    def: "A breast squamous cell carcinoma characterized by large epithelial cells that contain keratin." [url:https\://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI Metathesaurus&code=C1519486]␊
                                                                                                                                                                                      ^
SyntaxError: expected QuotedString

I think this error is caused by the file.
Do you have any suggestion?

**Comment by lschriml** [comment]
Good morning,
I would suggest using the doid.obo file. 
I have not used the protoOntology parser, I’m not sure what the error could be. 

Cheers,
Lynn

**Comment by beckyjackson** [comment]
It would appear this is an issue with the definition source: 
```
url:https\://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI Metathesaurus&code=C1519486
```

There should not be a space in this (NCI Metathesaurus), and that's what is causing the issue. I just pushed a fix for this to the edit file and it will be available in the next release.

If you need to use the OBO file now, you can replace that xref with:
```
url:https\://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C1519486
```

**Comment by lingling93** [comment]
Thank you for your quick replies.
doid.obo has the same issue.
I need the xref information to map DO to UMLS. I will try the json file.

**Comment by lschriml** [comment]
Thank you Lingling for pointing out this error !!
I have updated all of the production owl and obo files in the GitHub directory, 
https://github.com/DiseaseOntology/HumanDiseaseOntology/tree/master/src/ontology

Cheers,
Lynn

**Comment by lingling93** [comment]
Thank you so much !
You people are awesome !
